mongo3:
  hostname: mongo3
  image: mongo:3.2.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27018:27017"
    - "28018:28017"
  restart: always

mongo2:
  hostname: mongo2
  image: mongo:3.2.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27019:27017"
    - "28019:28017"
  restart: always

mongo1:
  hostname: mongo1
  image: mongo:3.2.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27017:27017"
    - "28017:28017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3
  restart: always

# This configures the MongoDB replicaset
mongosetup:
  hostname: mongosetup
  image: devialab/mongodb-replicaset
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  entrypoint: [ "/scripts/setup.sh" ]

  